-- Baby Shower App - Supabase Schema (Dedicated baby_shower schema)
-- Project: bkszmvfsfgvdwzacgmfz
-- Everything goes into its own schema for cleanliness

-- ============================================
-- CREATE DEDICATED SCHEMA
-- ============================================
create schema if not exists baby_shower;

-- ============================================
-- CLEANUP (drop old tables if they exist)
-- ============================================
drop table if exists baby_shower.submissions cascade;
drop table if exists public.guestbook cascade;
drop table if exists public.baby_pool cascade;
drop table if exists public.quiz cascade;
drop table if exists public.advice cascade;
drop table if exists public.voting cascade;

-- ============================================
-- SINGLE SUBMISSIONS TABLE (in baby_shower schema)
-- ============================================
create table if not exists baby_shower.submissions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    
    -- Guest info (common to all)
    name text not null,
    
    -- Activity type: 'guestbook', 'baby_pool', 'quiz', 'advice', 'voting'
    -- Note: baby_pool (not pool) to match frontend client expectations
    activity_type text not null,
    
    -- Activity-specific data (JSON for flexibility)
    activity_data jsonb default '{}'::jsonb
);

-- ============================================
-- RLS POLICIES (on baby_shower schema)
-- ============================================
alter table baby_shower.submissions enable row level security;

-- Drop existing policies if they exist
drop policy if exists "Allow anonymous reads" on baby_shower.submissions;
drop policy if exists "Allow anonymous inserts" on baby_shower.submissions;

-- Create policies
create policy "Allow anonymous reads" on baby_shower.submissions
    for select using (true);

create policy "Allow anonymous inserts" on baby_shower.submissions
    for insert with check (true);

-- ============================================
-- REALTIME (only TABLE, not views!)
-- ============================================
drop publication if exists supabase_realtime;
create publication supabase_realtime;
alter publication supabase_realtime add table baby_shower.submissions;

-- ============================================
-- INDEXES
-- ============================================
drop index if exists idx_baby_shower_activity;
drop index if exists idx_baby_shower_name;
drop index if exists idx_baby_shower_created;

create index idx_baby_shower_activity on baby_shower.submissions(activity_type);
create index idx_baby_shower_name on baby_shower.submissions(name);
create index idx_baby_shower_created on baby_shower.submissions(created_at desc);

-- ============================================
-- HELPER VIEWS (no realtime on views!)
-- ============================================
drop view if exists baby_shower.submissions_count;
drop view if exists baby_shower.guestbook_entries;
drop view if exists baby_shower.pool_entries;
drop view if exists baby_shower.quiz_entries;
drop view if exists baby_shower.advice_entries;
drop view if exists baby_shower.vote_counts;

create or replace view baby_shower.submissions_count as
select 
    activity_type,
    count(*) as total,
    min(created_at) as first_submission,
    max(created_at) as last_submission
from baby_shower.submissions
group by activity_type;

create or replace view baby_shower.guestbook_entries as
select * from baby_shower.submissions 
where activity_type = 'guestbook'
order by created_at desc;

create or replace view baby_shower.pool_entries as
select * from baby_shower.submissions 
where activity_type = 'baby_pool'
order by created_at desc;

create or replace view baby_shower.quiz_entries as
select * from baby_shower.submissions 
where activity_type = 'quiz'
order by created_at desc;

create or replace view baby_shower.advice_entries as
select * from baby_shower.submissions 
where activity_type = 'advice'
order by created_at desc;

create or replace view baby_shower.vote_counts as
select 
    jsonb_array_elements_text(activity_data->'names') as baby_name,
    count(*) as vote_count
from baby_shower.submissions 
where activity_type = 'voting'
group by baby_name
order by vote_count desc;

-- ============================================
-- SCHEMA PERMISSIONS (required after Supabase hardening)
-- https://supabase.com/docs/guides/database/hardening-data-api
-- ============================================

-- Grant USAGE on baby_shower schema to anon and authenticated roles
GRANT USAGE ON SCHEMA baby_shower TO anon, authenticated;

-- Grant table permissions
GRANT SELECT, INSERT ON baby_shower.submissions TO anon, authenticated;

-- Grant view permissions
GRANT SELECT ON baby_shower.submissions_count TO anon, authenticated;
GRANT SELECT ON baby_shower.guestbook_entries TO anon, authenticated;
GRANT SELECT ON baby_shower.pool_entries TO anon, authenticated;
GRANT SELECT ON baby_shower.quiz_entries TO anon, authenticated;
GRANT SELECT ON baby_shower.advice_entries TO anon, authenticated;
GRANT SELECT ON baby_shower.vote_counts TO anon, authenticated;

-- Grant service_role for realtime
GRANT USAGE ON SCHEMA baby_shower TO service_role;
GRANT SELECT, INSERT ON baby_shower.submissions TO service_role;
GRANT SELECT ON baby_shower.submissions_count TO service_role;
GRANT SELECT ON baby_shower.vote_counts TO service_role;
