-- Check if baby_shower schema exists
select schema_name 
from information_schema.schemata 
where schema_name = 'baby_shower';

-- If not found, create it
create schema if not exists baby_shower;

-- Check if table exists
select table_name 
from information_schema.tables 
where table_schema = 'baby_shower' 
and table_name = 'submissions';

-- If table doesn't exist, create it
create table if not exists baby_shower.submissions (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    name text not null,
    activity_type text not null,
    activity_data jsonb default '{}'::jsonb
);

-- Add RLS
alter table baby_shower.submissions enable row level security;

-- Drop old policies if exist
drop policy if exists "Allow anonymous reads" on baby_shower.submissions;
drop policy if exists "Allow anonymous inserts" on baby_shower.submissions;

-- Create policies
create policy "Allow anonymous reads" on baby_shower.submissions for select using (true);
create policy "Allow anonymous inserts" on baby_shower.submissions for insert with check (true);

-- Enable realtime
drop publication if exists supabase_realtime;
create publication supabase_realtime;
alter publication supabase_realtime add table baby_shower.submissions;

-- Verify
select * from baby_shower.submissions limit 1;
